name: .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4
      
    - name: MSBuild einrichten
      uses: microsoft/setup-msbuild@v1.1

    - name: NuGet einrichten
      uses: NuGet/setup-nuget@v1

    - name: Abhängigkeiten wiederherstellen
      shell: pwsh
      run: |
        $solutionFiles = Get-ChildItem -Recurse -Filter *.sln
        foreach ($solutionFile in $solutionFiles) {
          nuget restore $solutionFile.FullName
        }

    - name: Build und Test
      shell: pwsh
      run: |
        $solutionFiles = Get-ChildItem -Recurse -Filter *.sln
        foreach ($solutionFile in $solutionFiles) {
          msbuild $solutionFile.FullName /p:Configuration=Release /p:RunCodeAnalysis=true
        }
