name: .NET CI 3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TESTneu2/TESTneu2.sln  # Gib hier den tatsächlichen Pfad zu deiner .sln-Datei an

    - name: Build
      run: dotnet build TESTneu2/TESTneu2.sln --configuration Release  # Gib hier den tatsächlichen Pfad zu deiner .sln-Datei an

    - name: Test
      run: dotnet test TESTneu2/TESTneu2.sln --configuration Release  # Gib hier den tatsächlichen Pfad zu deiner .sln-Datei an
