name: .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore dependencies
      run: nuget restore TESTneu2/TESTneu2.sln
    - name: Build
      run: msbuild TESTneu2/TESTneu2.sln /p:Configuration=Release
    - name: Test
      run: |
        $testDlls = Get-ChildItem -Path **\*Tests.dll -Recurse | Select-Object -ExpandProperty FullName
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" $testDlls
      shell: pwsh

